### ISSUE TITLE
Bug Report: rare NoSuchElementException when multiple players log in

### ISSUE THREAD

**Issue by jonesdevelopment** [jonesdevelopment/sonar#18]
### General information

```
[13:18:11] [Velocity Async Event Executor - #0/ERROR] [com.velocitypowered.proxy.event.VelocityEventManager]: Couldn't pass PreLoginEvent to sonar
java.util.NoSuchElementException: minecraft-decoder
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at xyz.jonesdev.sonar.common.fallback.traffic.TrafficChannelHooker.hook(TrafficChannelHooker.java:31) ~[?:?]
	at xyz.jonesdev.sonar.velocity.fallback.FallbackListener.handle(FallbackListener.java:121) ~[?:?]
	at xyz.jonesdev.sonar.velocity.fallback.Lmbda$12.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) [?:?]
```

### Steps to reproduce

1. Let multiple bots/players enter the verification with high ping
2. Wait for the error message to pop up in console

**Comment by jonesdevelopment** [comment]
Update: This *might* be caused by TCPShield. (Unconfirmed)
I will fix this issue since it's a problem within Sonar.

**Comment by jonesdevelopment** [comment]
Should be fixed in https://github.com/jonesdevelopment/sonar/commit/f97f655e8f851af1416bb65051b23e736e1d0182
