### ISSUE TITLE
Incompatible with 1.12.2

### ISSUE THREAD

**Issue by PHE-yeji** [jonesdevelopment/sonar#348]
### General information

[21:06:39 ERROR]: Could not load 'plugins\Sonar-Bukkit.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: xyz/jonesdev/sonar/bukkit/SonarBukkitPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-Akarin-"104045e"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:333) ~[SimplePluginManager.class:git-Akarin-"104045e"]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255) ~[SimplePluginManager.class:git-Akarin-"104045e"]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:321) ~[CraftServer.class:git-Akarin-"104045e"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222) ~[DedicatedServer.class:git-Akarin-"104045e"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[MinecraftServer.class:git-Akarin-"104045e"]
        at java.lang.Thread.run(Thread.java:855) ~[?:1.8.0_412]
Caused by: java.lang.UnsupportedClassVersionError: xyz/jonesdev/sonar/bukkit/SonarBukkitPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_412]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:841) ~[?:1.8.0_412]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:145) ~[?:1.8.0_412]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[PluginClassLoader.class:git-Akarin-"104045e"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PluginClassLoader.class:git-Akarin-"104045e"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:427) ~[?:1.8.0_412]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:360) ~[?:1.8.0_412]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_412]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_412]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[PluginClassLoader.class:git-Akarin-"104045e"]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[JavaPluginLoader.class:git-Akarin-"104045e"]
        ... 6 more

### Steps to reproduce

Sonar does not support Java8

### Sonar dump

Sorry ，load failed

**Comment by F3F5** [comment]
just wait new update, thanks for reporting

**Comment by jonesdevelopment** [comment]
> Sonar does not support Java 8

That's correct. Upgrade to Java 11+.
Not to mention that Bukkit isn't supported yet.
Read more: https://docs.jonesdev.xyz/sonar/supported-versions
