### ISSUE TITLE
plugin does not start

### ISSUE THREAD

**Issue by shama2710** [jonesdevelopment/sonar#383]
### General information

the plugin fails to start with error in console:

[ERROR]: Couldn't pass ProxyInitializeEvent to sonar
java.lang.NoSuchMethodError: 'int net.kyori.adventure.nbt.CompoundBinaryTag.size()'
        at xyz.jonesdev.sonar.common.fallback.protocol.packets.configuration.RegistryDataPacket.of(RegistryDataPacket.java:71) ~[?:?]
        at xyz.jonesdev.sonar.common.fallback.protocol.FallbackPreparer.<clinit>(FallbackPreparer.java:55) ~[?:?]
        at xyz.jonesdev.sonar.common.boot.SonarBootstrap.reload(SonarBootstrap.java:155) ~[?:?]
        at xyz.jonesdev.sonar.common.boot.SonarBootstrap.initialize(SonarBootstrap.java:113) ~[?:?]
        at xyz.jonesdev.sonar.velocity.SonarVelocityPlugin.handle(SonarVelocityPlugin.java:54) ~[?:?]
        at xyz.jonesdev.sonar.velocity.Lmbda$15.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[core.jar:3.2.0-SNAPSHOT (git-07a525be-b296)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[core.jar:3.2.0-SNAPSHOT (git-07a525be-b296)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[core.jar:3.2.0-SNAPSHOT (git-07a525be-b296)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
        
help solve the problem

### Steps to reproduce

start server

### Sonar dump

/sonar dump - not working

### Additional information

no

**Comment by jonesdevelopment** [comment]
Update Velocity. Only Velocity 3.3.0 b330 and above are supported. The Velocity version you're using is very old.

**Comment by jonesdevelopment** [comment]
Link to the documentation: https://docs.jonesdev.xyz/sonar/supported-versions
