### ISSUE TITLE
Bug Report  - Velocity on startup

### ISSUE THREAD

**Issue by rageyh** [jonesdevelopment/sonar#419]
### General information

Hi, practically when I start proxy (velocity) it gives me this error in the console (fortunately without disabling the plugin)

### Steps to reproduce

1. start velocity server

### Sonar dump

Generated dump: {"memory":{"total":"1 GiB","max":"1 GiB","free":"822.1 MiB","used":"201.9 MiB"},"runtime":{"virtualCores":6,"jvmArguments":["-Xms1024M","-Xmx1024M","-XX:+UseG1GC","-XX:G1HeapRegionSize\u003d4M","-XX:+UnlockExperimentalVMOptions","-XX:+ParallelRefProcEnabled","-XX:+AlwaysPreTouch","-XX:MaxInlineLevel\u003d15"],"vmName":"OpenJDK 64-Bit Server VM","vmVendor":"Oracle Corporation","vmVersion":"17.0.2+8-86"},"os":{"name":"Linux","arch":"amd64","version":"5.15.0-126-generic"},"sonar":{"version":"2.1.17 (adef9d9c)","platform":"VELOCITY","gitBranch":"main","gitCommit":"adef9d9c"}}

### Additional information

[18:22:23 ERROR]: Exception in thread "pool-32-thread-1" java.lang.ExceptionInInitializerError
[18:22:23 ERROR]:       at xyz.jonesdev.sonar.captcha.StandardCaptchaGenerator.drawCharacters(StandardCaptchaGenerator.java:127)
[18:22:23 ERROR]:       at xyz.jonesdev.sonar.captcha.StandardCaptchaGenerator.createImage(StandardCaptchaGenerator.java:79)
[18:22:23 ERROR]:       at xyz.jonesdev.sonar.common.fallback.protocol.CaptchaPreparer.lambda$prepare$0(CaptchaPreparer.java:65)
[18:22:23 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[18:22:23 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[18:22:23 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[18:22:23 ERROR]: Caused by: java.lang.IllegalStateException: java.io.IOException: Problem reading font data.
[18:22:23 ERROR]:       at xyz.jonesdev.sonar.captcha.StandardTTFFontProvider.loadFont(StandardTTFFontProvider.java:46)
[18:22:23 ERROR]:       at xyz.jonesdev.sonar.captcha.StandardTTFFontProvider.<clinit>(StandardTTFFontProvider.java:35)
[18:22:23 ERROR]:       ... 6 more
[18:22:23 ERROR]: Caused by: java.io.IOException: Problem reading font data.
[18:22:23 ERROR]:       at java.desktop/java.awt.Font.createFont0(Font.java:1208)
[18:22:23 ERROR]:       at java.desktop/java.awt.Font.createFont(Font.java:1076)
[18:22:23 ERROR]:       at xyz.jonesdev.sonar.captcha.StandardTTFFontProvider.loadFont(StandardTTFFontProvider.java:42)
[18:22:23 ERROR]:       ... 7 more

**Comment by jonesdevelopment** [comment]
Make sure you have fonts installed on your machine.

Your JDK might not have built-in font support.

**Comment by jonesdevelopment** [comment]
Try `sudo apt-get install fontconfig` or search online for how to install fonts.

Also make sure to update Sonar—you're a version behind.

**Comment by sprytex** [comment]
> Try `sudo apt-get install fontconfig` or search online for how to install fonts.
> 
> Also make sure to update Sonar—you're a version behind.

maybe make a text with a recommendation for a certain error? then there would be fewer issues, it's already 2 cases i saw with sonar
