### ISSUE TITLE
Bug Report: Missing relocations breaking existing classes

### ISSUE THREAD

**Issue by arm4xlll** [jonesdevelopment/sonar#46]
### General information

startup plugin error

### Steps to reproduce

im only add sonar to plugins and start server

### Sonar dump

not works (plugin not load)

### Additional information

[19:38:30] [Velocity Async Event Executor - #0/INFO] [sonar]: Successfully booted in 0.007s!
[19:38:30] [Velocity Async Event Executor - #0/INFO] [sonar]: Initializing shared components...
[19:38:30] [Velocity Async Event Executor - #0/ERROR] [com.velocitypowered.proxy.event.VelocityEventManager]: Couldn't pass ProxyInitializeEvent to sonar
java.lang.NoSuchMethodError: 'net.kyori.adventure.nbt.LongArrayBinaryTag net.kyori.adventure.nbt.LongArrayBinaryTag.longArrayBinaryTag(long[])'
	at xyz.jonesdev.sonar.common.fallback.protocol.packets.EmptyChunkData.prepareNBT(EmptyChunkData.java:71) ~[?:?]
	at xyz.jonesdev.sonar.common.fallback.protocol.packets.EmptyChunkData.<clinit>(EmptyChunkData.java:65) ~[?:?]
	at xyz.jonesdev.sonar.common.fallback.protocol.FallbackPreparer.<clinit>(FallbackPreparer.java:77) ~[?:?]
	at xyz.jonesdev.sonar.common.boot.SonarBootstrap.reload(SonarBootstrap.java:111) ~[?:?]
	at xyz.jonesdev.sonar.common.boot.SonarBootstrap.initialize(SonarBootstrap.java:79) ~[?:?]
	at xyz.jonesdev.sonar.velocity.SonarVelocityPlugin.handle(SonarVelocityPlugin.java:64) ~[?:?]
	at xyz.jonesdev.sonar.velocity.Lmbda$21.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[server.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[server.jar:3.2.0-SNAPSHOT (git-bda1430d-b259)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by jonesdevelopment** [comment]
Which version of Velocity are you using?

**Comment by arm4xlll** [comment]
> Which version of Velocity are you using?

![image](https://github.com/jonesdevelopment/sonar/assets/109166895/ec7a0118-2df7-4578-8c07-8cd2bc4b40ff)

**Comment by jonesdevelopment** [comment]
Could you try the latest release (b265)?
It seems like some classes couldn't be found... very strange

**Comment by arm4xlll** [comment]
> Could you try the latest release (b265)? It seems like some classes couldn't be found... very strange

oh my bad, it work! thanks

**Comment by jonesdevelopment** [comment]
Still pretty strange. It should not happen on older releases. I'll look into the NoSuchMethodError since I do think this is an issue.
It might be because I'm not relocating the dependencies and it tries to use velocity's classes. I never thought about that.

**Comment by jonesdevelopment** [comment]
```
[17:58:17 ERROR]: Couldn't pass ProxyInitializeEvent to sonar
java.lang.NoSuchMethodError: 'net.kyori.adventure.nbt.LongArrayBinaryTag net.kyori.adventure.nbt.LongArrayBinaryTag.longArrayBinaryTag(long[])'
	at xyz.jonesdev.sonar.common.fallback.protocol.packets.EmptyChunkData.prepareNBT(EmptyChunkData.java:71) ~[?:?]
	at xyz.jonesdev.sonar.common.fallback.protocol.packets.EmptyChunkData.<clinit>(EmptyChunkData.java:65) ~[?:?]
	at xyz.jonesdev.sonar.common.fallback.protocol.FallbackPreparer.<clinit>(FallbackPreparer.java:77) ~[?:?]
	at xyz.jonesdev.sonar.common.boot.SonarBootstrap.reload(SonarBootstrap.java:111) ~[?:?]
	at xyz.jonesdev.sonar.common.boot.SonarBootstrap.initialize(SonarBootstrap.java:79) ~[?:?]
	at xyz.jonesdev.sonar.velocity.SonarVelocityPlugin.handle(SonarVelocityPlugin.java:64) ~[?:?]
	at xyz.jonesdev.sonar.velocity.Lmbda$4.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1623) [?:?]
```
I get the same error on b259 — I will add a fix for backwards compatibility. Thank you for reporting this.

**Comment by arm4xlll** [comment]
> ```
> [17:58:17 ERROR]: Couldn't pass ProxyInitializeEvent to sonar
> java.lang.NoSuchMethodError: 'net.kyori.adventure.nbt.LongArrayBinaryTag net.kyori.adventure.nbt.LongArrayBinaryTag.longArrayBinaryTag(long[])'
> 	at xyz.jonesdev.sonar.common.fallback.protocol.packets.EmptyChunkData.prepareNBT(EmptyChunkData.java:71) ~[?:?]
> 	at xyz.jonesdev.sonar.common.fallback.protocol.packets.EmptyChunkData.<clinit>(EmptyChunkData.java:65) ~[?:?]
> 	at xyz.jonesdev.sonar.common.fallback.protocol.FallbackPreparer.<clinit>(FallbackPreparer.java:77) ~[?:?]
> 	at xyz.jonesdev.sonar.common.boot.SonarBootstrap.reload(SonarBootstrap.java:111) ~[?:?]
> 	at xyz.jonesdev.sonar.common.boot.SonarBootstrap.initialize(SonarBootstrap.java:79) ~[?:?]
> 	at xyz.jonesdev.sonar.velocity.SonarVelocityPlugin.handle(SonarVelocityPlugin.java:64) ~[?:?]
> 	at xyz.jonesdev.sonar.velocity.Lmbda$4.execute(Unknown Source) ~[?:?]
> 	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
> 	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
> 	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-258.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
> 	at java.lang.Thread.run(Thread.java:1623) [?:?]
> ```
> 
> I get the same error on b259 — I will add a fix for backwards compatibility. Thank you for reporting this.

thank you too

**Comment by jonesdevelopment** [comment]
Velocity builds <260 are unsupported because they updated to adventure 4.14.0 in https://github.com/PaperMC/Velocity/pull/1034/
I will push a fix to another feature branch that will be implemented later. I cannot fix the incompatibility as Sonar uses a different adventure version, however, I can fix potential other issues caused by missing relocations.
BungeeCord & Spigot are unaffected. Velocity b260 or higher are fine as well.

**Comment by Maksim-Lipenka** [comment]
![image](https://github.com/jonesdevelopment/sonar/assets/43496357/cc4f0333-96c1-4a6e-8ab9-a68949cb5201)
@jonesdevelopment

**Comment by jonesdevelopment** [comment]
> @jonesdevelopment 

Velocity 3.3.0 is not supported yet. Please use Velocity 3.2.0.
It's not recommended to use 3.3.0 yet as all builds are marked as "experimental"
![image](https://github.com/jonesdevelopment/sonar/assets/73846784/5d06a023-70c7-4282-a9bd-630dd19b01a0)
Just wait for 2.0.12 to release and use Velocity 3.2.0 in the meantime.

**Comment by jonesdevelopment** [comment]
It's not recommended to use 3.3.0 yet as all builds are marked as "experimental"
![image](https://github.com/jonesdevelopment/sonar/assets/73846784/5d06a023-70c7-4282-a9bd-630dd19b01a0)
Just wait for 2.0.12 to release and use Velocity 3.2.0 in the meantime.

**Comment by Maksim-Lipenka** [comment]
> > @jonesdevelopment
> 
> Velocity 3.3.0 is not supported yet. Please use Velocity 3.2.0. It's not recommended to use 3.3.0 yet as all builds are marked as "experimental" ![image](https://private-user-images.githubusercontent.com/73846784/292280627-5d06a023-70c7-4282-a9bd-630dd19b01a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxODE3OTYsIm5iZiI6MTcwMzE4MTQ5NiwicGF0aCI6Ii83Mzg0Njc4NC8yOTIyODA2MjctNWQwNmEwMjMtNzBjNy00MjgyLWE5YmQtNjMwZGQxOWIwMWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE3NTgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NDRmMTA1ZmM3YTQ4NWM2NWVlZDY5YjViNGVhZThkYmI2OGIyNmQyYmJjNzI2NTBjN2I3MDJjYzcxZjU3NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5RGxAvXMOb_fyLkfSldTsTZguvUwZoBJ64gXKup3aLc) Just wait for 2.0.12 to release and use Velocity 3.2.0 in the meantime.

So, you are saying that velocity 1.20.4 is not supported, right?

**Comment by jonesdevelopment** [comment]
> So, you are saying that velocity 1.20.4 is not supported, right?

Velocity 3.3.0 is not supported yet because of multiple API changes. The builds you can download on PaperMC's website state that it's "experimental" which means you should not use them until the builds have been through some testing. Sonar 2.0.11 does not support these API changes yet (same with some other plugins that failed to load in your screenshot). However, Sonar 2.0.12 will feature support for Velocity 3.3.0 (ETA: 25/12/2023)
