### ISSUE TITLE
[Request] compatible with botfilter

### ISSUE THREAD

**Issue by FallenCrystal** [jonesdevelopment/sonar#7]
### General information

just compatible with it.

### Reason

BotFilter is really good.

### Additional information

u dont need to change anything else. just dont replace VarImtFrameDecoder with sonar's own compatibility.

### Can this feature be found in other existing plugins?

Unsure

**Comment by xism4** [comment]
> u dont need to change anything else. just dont replace VarIntFrameDecoder with sonar's own decoder.

Can you send me the log? I think I can fix it.

The velocity VarIntFrameDecoder is much better than the bungeecord one and with less inconsistencies.

I would recommend you to try other alternatives, botfilter is abandoned on improvements.

**Comment by FallenCrystal** [comment]
it seems Sonar's ExceptionHandler is preventing it from printing logs. i need a little more time.

**Comment by FallenCrystal** [comment]
> Can you send me the log? I think I can fix it.

```
18:49:23 [SEVERE] java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.protocol.Varint21FrameDecoder.set119(boolean)" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null
18:49:23 [SEVERE]     at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:362)
18:49:23 [SEVERE]     at jones.sonar.bungee.network.handler.PlayerHandler.handle(PlayerHandler.java:173)
18:49:23 [SEVERE]     at net.md_5.bungee.protocol.packet.Handshake.handle(Handshake.java:51)
18:49:23 [SEVERE]     at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:121)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
18:49:23 [SEVERE]     at org.geysermc.floodgate.addon.data.CommonDataHandler.disablePacketQueue(CommonDataHandler.java:136)
18:49:23 [SEVERE]     at org.geysermc.floodgate.addon.data.CommonDataHandler.handle(CommonDataHandler.java:75)
18:49:23 [SEVERE]     at org.geysermc.floodgate.addon.data.BungeeProxyDataHandler.channelRead(BungeeProxyDataHandler.java:91)
18:49:23 [SEVERE]     at org.geysermc.floodgate.addon.data.CommonDataHandler.channelRead(CommonDataHandler.java:178)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
18:49:23 [SEVERE]     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
18:49:23 [SEVERE]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
18:49:23 [SEVERE]     at org.geysermc.floodgate.addon.data.PacketBlocker.channelRead(PacketBlocker.java:76)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
18:49:23 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
18:49:23 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
18:49:23 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
18:49:23 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
18:49:23 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:266)
18:49:23 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:536)
18:49:23 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
18:49:23 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
18:49:23 [SEVERE]     at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
18:49:23 [SEVERE]     at org.geysermc.floodgate.inject.bungee.BungeeInjector$BungeeClientToProxyInjectInitializer.channelRead(BungeeInjector.java:160)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
18:49:23 [SEVERE]     at jones.sonar.bungee.network.handler.BungeeHandler.channelRead(BungeeHandler.java:57)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
18:49:23 [SEVERE]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
18:49:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
18:49:23 [SEVERE]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
18:49:23 [SEVERE]     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
18:49:23 [SEVERE]     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
18:49:23 [SEVERE]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
18:49:23 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
18:49:23 [SEVERE]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
18:49:23 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:1589)
```
maybe we should provide a boolean?

**Comment by jonesdevelopment** [comment]
Could a custom start up flag which disables the custom Varint21FrameDecoder (basically Velocity's) fix this issue?

**Comment by FallenCrystal** [comment]
> Could a custom start up flag which disables the custom Varint21FrameDecoder (basically Velocity's) fix this issue?

i didnt know there was this. if u can tell me. i can go and try it. or do u mean to add this feature?

**Comment by jonesdevelopment** [comment]
> > Could a custom start up flag which disables the custom Varint21FrameDecoder (basically Velocity's) fix this issue?
> 
> i didnt know there was this. if u can tell me. i can go and try it. or do u mean to add this feature?

I haven't added such a feature yet but I could add it if it helps.

I'm actually working on Sonar 2.0, a completely rewritten version of Sonar.
You can join my [Discord server](https://jonesdev.xyz/discord) if you want to receive update notifications, etc.

I also recommend using [Velocity](https://velocitypowered.com/) instead of BungeeCord or Waterfall. It's a lot better more modern and will be supported by Sonar 2.0.

**Comment by FallenCrystal** [comment]
> I also recommend using [Velocity](https://velocitypowered.com/) instead of BungeeCord or Waterfall. It's a lot better and more modern and will be supported by Sonar 2.0.

ik but i still use bungeecord for a few reasons. im still not very familiar with velocity. and there are various reasons preventing me from migrating to it. if i plan to remake my proxy afterwards i might think about it

> I haven't added such a feature yet but I could add it if it helps.

ah i can do it. but my computer is broken. 
actually.. botFilter may indeed not be that worth using. but most people just need a good antibot scheme. what they see is the limbo verification code. and not the coding that looks a little bad. although ping+join can already block most bots.
although the use of velocity+limbofilter is advocated. but there are still people who r using botfilter. bungeecord is still in high demand. ik velocity is best. but migrating a platform is not a simple task.

**Comment by xism4** [comment]
> set119

This can be skiped easily
